name: gohugo.io
on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest
        extended: true

    - name: Cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-hugomod-${{ hashFiles('go.sum') }}
        path: /tmp/hugo_cache
        restore-keys: ${{ runner.os }}-hugomod-

    - name: Build
      run: hugo --minify

    - name: Upload
      uses: actions/upload-pages-artifact@v1
      with:
        name: github-pages
        path: ./public
        retention-days: 1

    - name: Publish
      uses: actions/deploy-pages@v2
